const subjects = [
	["Accounting", 2],
	["Agricultural Economics", 2],
	["Agricultural Science", 2],
	["Ancient Greek", 2],
	["Applied Maths", 2],
	["Arabic", 2],
	["Art", 2],
	["Biology", 2],
	["Bulgarian", 1],
	["Business", 2],
	["Chemistry", 2],
	["Chinese", 2],
	["Classical", 2],
	["Computer Science", 2],
	["Construction", 2],
	["Croatian", 1],
	["Czech", 1],
	["Danish", 1],
	["Design & Communication Graphics", 2],
	["Dutch", 1],
	["Economics", 2],
	["Engineering", 2],
	["English", 2],
	["Estonian", 1],
	["Finnish", 1],
	["French", 2],
	["Geography", 2],
	["German", 2],
	["Hebrew", 2],
	["History", 2],
	["Home Economics", 2],
	["Hungarian", 1],
	["Irish", 2],
	["Italian", 2],
	["Japanese", 2],
	["Latin", 2],
	["Latvian", 1],
	["LCVP", 0],
	["Lithuanian", 1],
	["Maltese", 1],
	["Maths", 2],
	["Modern Greek", 2],
	["Music", 2],
	["Physical Education", 2],
	["Physics", 2],
	["Physics & Chemistry", 2],
	["Polish", 1],
	["Politics & Society", 2],
	["Portuguese", 1],
	["Religion", 2],
	["Romanian", 1],
	["Russian", 2],
	["Slovakian", 1],
	["Slovenian", 1],
	["Spanish", 2],
	["Swedish", 1],
	["Technology", 2]
];

const commonSubjects = ["maths", "english", "irish", "biology", "chemistry", "physics", "geography", "history", "art", "music", "french", "spanish", "german", "lcvp"];
const percentages = ["90% - 100%", "80% - 89%", "70% - 79%", "60% - 69%", "50% - 59%", "40% - 49%", "30% - 39%", "0% - 29%"];

const points = {
	h1: 100,
	h2: 88,
	h3: 77,
	h4: 66,
	h5: 56,
	h6: 46,
	h7: 37,
	h8: 0,
	o1: 56,
	o2: 46,
	o3: 37,
	o4: 28,
	o5: 20,
	o6: 12,
	o7: 0,
	o8: 0,
	distinction: 66,
	merit: 46,
	pass: 28
}